### ISSUE TITLE
Translate to another language

### ISSUE THREAD

**Issue by zhyuri** [campoy/go-tooling-workshop#38]
Hi, I'm thinking maybe there could be an i18n support for this project.
If you are thinking of the same thing, let's discuss how to do it, in a different branch or a different directory?

I'm willing to help translating to Chinese.

**Comment by campoy** [comment]
I think it'd be easier to keep it as a different repository, but yes it'd be awesome to have!

How do you think you could do it so the translations are kept up to date with the original content?

By the way, you can totally create the repo without my permission, as long as you add a link to this repository.

**Comment by zhyuri** [comment]
As far as I know, there isn't a translate tools helps you keep up to date with the original content.

My thought is starting a side project to build a translate tool based on some kind of VCS like Git help translator keep up to date. With the help of 'Diff' ability, people can easily find out what happened with the origin.

Maybe we can build this together? Or if anyone you knew is interested with the idea, let's make it happen.

**Comment by campoy** [comment]
Another option would be to start having releases of this project, which will be increased only when a considerable change has been added.
That way translations can refer to what release they translated, and when they want to update it they can use git diff to check what changed since that release

Wdyt?

**Comment by zhyuri** [comment]
Yes, I agree. It would be better for official translation project.
Since we have the ability to provide 'line level' even 'word level' diff for translations. Whether based on the 'released version' or 'working version' will depends on users.

I think the most important part of this idea is that it provides a possibility of tracking the updates from the origin, and give a mapping between origin one and yours on 'line level'. We can use it as a translation helper, Github Gist comment, etc. People write their own content based on the origin one and follow the updates, then they can correct their translations, comments or even use the update history as an evidence.

Based on such a infrastructure we can accomplish a lot of interesting things.
