### ISSUE TITLE
Missing import in "Testing Go programs"

### ISSUE THREAD

**Issue by inkel** [campoy/go-tooling-workshop#43]
First of all, thank you for taking the time of writing this workshop! It has been really helpful to me.

While reading the chapter on testing, in the [_What package contains the tests?_](https://github.com/campoy/go-tooling-workshop/blob/master/3-dynamic-analysis/2-testing/1-go-test.md#what-package-contains-the-tests) section it seems that you're missing an import. (I've linked the line numbers but GitHub and Markdown rocks and sucks at the same time).

This is the example:

```go
package sum_test

import "testing"

func TestAll(t *testing.T) {
	// Implement the body of this test, calling sum.All.
}
```

Unless I'm mistaken, you're missing an import to your `sum` package.

~~I'd have send a PR but I've no idea what's the workflow you have for making changes to this repo (e.g. using [`embedmd`](https://github.com/campoy/embedmd)). Also, what would be the import path?~~ I've let `goimports` manage to come up with the import path. I hope that's ok.

**Comment by campoy** [comment]
As discussed in the PR #44 closing this.
